spring:
  application:
    name: movie-reviewer
  h2:
    console:
      enabled: true
  datasource:
    url: 'jdbc:h2:mem:movie-reviewer-data-source'
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    # Schema.sql and data.sql executed prior to Hibernate Schema Initialization. TO avoid this,
    defer-datasource-initialization: true
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace
